import{a as L,S as b,i as s}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const w="https://pixabay.com",S="/api/",q="55024332-4e4fe5cdde5981dd2414e779d";let P=15;async function d(r,o){if(!r||!r.trim())throw new Error("Query cannot be empty");const t=new URLSearchParams({key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o}),a=`${w}${S}?${t}`;try{return(await L.get(a)).data}catch(e){throw console.error("Error fetching images:",e),e}}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".btn"),v=new b(".gallery a",{captionsData:"alt",captionDelay:250});function f(r){const o=r.map(t=>`<li class="gallery-item">
  <a href="${t.largeImageURL}">
    <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image" />
  </a>
  <div class="info">
  <p class="info-item"><b>Likes:</b> <span>${t.likes}</span></p>
  <p class="info-item"><b>Views:</b> <span>${t.views}</span></p>
  <p class="info-item"><b>Comments:</b> <span>${t.comments}</span></p>
  <p class="info-item"><b>Downloads:</b> <span>${t.downloads}</span></p>
</div>
</li>`).join("");u.insertAdjacentHTML("beforeend",o),v.refresh()}function $(){u.innerHTML=""}function h(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function R(){p.classList.remove("hidden")}function i(){p.classList.add("hidden")}const E=document.querySelector(".form"),O=document.querySelector(".btn");let y="";E.addEventListener("submit",A);O.addEventListener("click",x);let c=1;async function x(){h();try{c+=1;const r=await d(y,c);f(r.hits);const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=r.totalHits&&(i(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}async function A(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(y=o,!o){s.warning({message:"Please enter a search query!",position:"topRight"});return}$(),h(),i();try{c=1;const t=await d(o,c);if(t.hits.length===0){i(),s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(t.hits),document.querySelectorAll(".gallery-item").length<t.totalHits?R():i()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g(),r.target.elements["search-text"].select()}}
//# sourceMappingURL=index.js.map
