import{a as b,S as w,i as a}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const S="https://pixabay.com",q="/api/",v="55024332-4e4fe5cdde5981dd2414e779d";let P=15;async function d(r,o){if(!r||!r.trim())throw new Error("Query cannot be empty");const t=new URLSearchParams({key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o}),n=`${S}${q}?${t}`;try{return(await b.get(n)).data}catch(e){throw console.error("Error fetching images:",e),e}}const u=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".btn"),R=new w(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const o=r.map(t=>`<li class="gallery-item">
  <a href="${t.largeImageURL}">
    <img src="${t.webformatURL}" alt="${t.tags}" class="gallery-image" />
  </a>
  <div class="info">
  <p class="info-item"><b>Likes:</b> <span>${t.likes}</span></p>
  <p class="info-item"><b>Views:</b> <span>${t.views}</span></p>
  <p class="info-item"><b>Comments:</b> <span>${t.comments}</span></p>
  <p class="info-item"><b>Downloads:</b> <span>${t.downloads}</span></p>
</div>
</li>`).join("");u.insertAdjacentHTML("beforeend",o),R.refresh()}function $(){u.innerHTML=""}function f(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function y(){m.classList.remove("hidden")}function i(){m.classList.add("hidden")}const E=document.querySelector(".form"),O=document.querySelector(".btn");let L="";E.addEventListener("submit",A);O.addEventListener("click",x);let c=1;async function x(){i(),f();try{c+=1;const r=await d(L,c);p(r.hits);const o=document.querySelector(".gallery-item");if(o){const{height:n}=o.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}document.querySelectorAll(".gallery-item").length>=r.totalHits?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):y()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}async function A(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(L=o,!o){a.warning({message:"Please enter a search query!",position:"topRight"});return}$(),f(),i();try{c=1;const t=await d(o,c);if(t.hits.length===0){i(),a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(t.hits),document.querySelectorAll(".gallery-item").length<t.totalHits?y():(i(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g(),r.target.elements["search-text"].select()}}
//# sourceMappingURL=index.js.map
